Update Git repository using egup-single

diff --git a/support/install b/support/install
--- a/support/install
+++ b/support/install
@@ -1,46 +1,118 @@
 #!/usr/bin/env bash
-echo 1 "$1" 2 "$2" 3 "$3" 4 "$4" 5 "$5" 6 "$6" 7 "$7" 8 "$8" 9 "$9"
-fmwtkDestdir="$1"
-fmwtkPrefix="$2"
-fmwtkCapPrefix="$3"
-fmwtkExecPrefix="$4"
-fmwtkBindir="$5"
-fmwtkDatarootdir="$6"
-fmwtkDatadir="$7"
-fmwtkSysconfdir="$8"
-fmwtkSharedstatedir="$9"
-if ! [ -n "$fmwtkPrefix" ]; then
-    if ! [ -n "$fmwtkCapPrefix" ]; then
-        fmwtkPrefix="$fmwtkDestdir"/usr/local
+# shellcheck disable=SC1091
+source ember_bash_setup &> /dev/null
+#set -x
+
+#NOTE: MAINTENANCE: Manual error printing
+if [[ -z "$(ember-getconf emberSharedVersion)" ]]; then
+    printf '%b' '\033[1;31m' >&2
+    echo "ERROR: ember-shared is not properly installed! It must be installed before installing eite." >&2
+    printf '%b' '\033[0m' >&2
+    exit 1
+fi
+
+trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)."' ERR
+
+skipConfigFile="false"
+if [[ "$1" == "--skip-config-file" ]]; then
+    skipConfigFile="true"
+    shift
+fi
+
+overrideInstalledAppDataDir="/usr/share"
+overrideInstalledAppDataDirArg="${1#*=}"
+if [[ "$1" == "--override-data-dir="* ]] && [[ -n "$overrideInstalledAppDataDirArg" ]]; then
+    overrideInstalledAppDataDir="$overrideInstalledAppDataDirArg"
+fi
+shift
+
+emberPrefix="$(<support/.prefix)" || true
+emberMandir="$(<support/.mandir)" || true
+emberInfodir="$(<support/.infodir)" || true
+emberDatadir="$(<support/.datadir)" || true
+emberSysconfdir="$(<support/.sysconfdir)" || true
+emberLocalstatedir="$(<support/.localstatedir)" || true
+
+#echo 1 "$1" 2 "$2" 3 "$3" 4 "$4" 5 "$5" 6 "$6" 7 "$7" 8 "$8" 9 "$9"
+if [[ -z "$emberDestdir" ]] && [[ -n "$1" ]]; then
+    emberDestdir="$1"
+    shift
+fi
+if [[ -z "$emberPrefix" ]] && [[ -n "$1" ]]; then
+    emberPrefix="$1"
+    shift
+fi
+if [[ -z "$emberCapPrefix" ]] && [[ -n "$1" ]]; then
+    emberCapPrefix="$1"
+    shift
+fi
+if [[ -z "$emberExecPrefix" ]] && [[ -n "$1" ]]; then
+    emberExecPrefix="$1"
+    shift
+fi
+if [[ -z "$emberBindir" ]] && [[ -n "$1" ]]; then
+    emberBindir="$1"
+    shift
+fi
+if [[ -z "$emberDatarootdir" ]] && [[ -n "$1" ]]; then
+    emberDatarootdir="$1"
+    shift
+fi
+if [[ -z "$emberDatadir" ]] && [[ -n "$1" ]]; then
+    emberDatadir="$1"
+    shift
+fi
+if [[ -z "$emberSysconfdir" ]] && [[ -n "$1" ]]; then
+    emberSysconfdir="$1"
+    shift
+fi
+if [[ -z "$emberSharedstatedir" ]] && [[ -n "$1" ]]; then
+    emberSharedstatedir="$1"
+    shift
+fi
+if [[ -z "$emberPrefix" ]]; then
+    if [[ -z "$emberCapPrefix" ]]; then
+        emberPrefix=/usr/local
     else
-        fmwtkPrefix="$fmwtkCapPrefix"
+        emberPrefix="$emberCapPrefix"
     fi
 fi
-echo "fmwtkPrefix: $fmwtkPrefix"
-if ! [ -n "$fmwtkExecPrefix" ]; then
-    fmwtkExecPrefix="$fmwtkPrefix"
+emberPrefix="$emberDestdir$emberPrefix"
+#echo "emberPrefix: $emberPrefix"
+if [[ -z "$emberExecPrefix" ]]; then
+    emberExecPrefix="$emberPrefix"
+else
+    emberExecPrefix="$emberDestdir$emberExecPrefix"
 fi
-echo "fmwtkExecPrefix: $fmwtkExecPrefix"
-if ! [ -n "$fmwtkBindir" ]; then
-    fmwtkBindir="$fmwtkExecPrefix"/bin
+#echo "emberExecPrefix: $emberExecPrefix"
+if [[ -z "$emberBindir" ]]; then
+    emberBindir="$emberExecPrefix"/bin
 fi
-echo "fmwtkBindir: $fmwtkBindir"
-if ! [ -n "$fmwtkDatarootdir" ]; then
-    fmwtkDatarootdir="$fmwtkPrefix"/share
+#echo "emberBindir: $emberBindir"
+if [[ -z "$emberDatarootdir" ]]; then
+    emberDatarootdir="$emberPrefix"/share
 fi
-echo "fmwtkDatarootdir: $fmwtkDatarootdir"
-if ! [ -n "$fmwtkDatadir" ]; then
-    fmwtkDatadir="$fmwtkDatarootdir"
+#echo "emberDatarootdir: $emberDatarootdir"
+if [[ -z "$emberDatadir" ]]; then
+    emberDatadir="$emberDestdir$emberDatarootdir"
+else
+    emberDatadir="$emberDestdir$emberDatadir"
 fi
-echo "fmwtkDatadir: $fmwtkDatadir"
-if ! [ -n "$fmwtkSysconfdir" ]; then
-    fmwtkSysconfdir="$fmwtkPrefix"/etc
+#echo "emberDatadir: $emberDatadir"
+if [[ -z "$emberSysconfdir" ]]; then
+    emberSysconfdir="$emberPrefix"/etc
+else
+    emberSysconfdir="$emberPrefix$emberSysconfdir"
 fi
-echo "fmwtkSysconfdir: $fmwtkSysconfdir"
-if ! [ -n "$fmwtkSharedstatedir" ]; then
-    fmwtkSharedstatedir="$fmwtkPrefix"/var
+#echo "emberSysconfdir: $emberSysconfdir"
+if [[ -z "$emberSharedstatedir" ]]; then
+    emberSharedstatedir="$emberPrefix"/var
+else
+    emberSharedstatedir="$emberPrefix$emberSharedstatedir"
 fi
-echo "fmwtkSharedstatedir: $fmwtkSharedstatedir"
+#echo "emberSharedstatedir: $emberSharedstatedir"
+
+#### End of Makefile install script template ####
 
 export fmwtkBindir
 fmwtkBindirEsc="$(perl -0777 -e 'print(quotemeta($ENV{fmwtkBindir}))')"
