Update Git repository using egup-single

diff --git a/support/prepare b/support/prepare
--- a/support/prepare
+++ b/support/prepare
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 # shellcheck disable=SC1091
-source ember_bash_setup &> /dev/null
+source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
 #set -x
 
 trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)."' ERR
@@ -29,7 +29,7 @@ fi
 substitutePath() {
     defaultPath="${1//\//\\\/}"
     newPathVarName="$2"
-    export "$newPathVarName"
+    export "${newPathVarName?}"
     local pathEsc
     pathEsc="$(perl -0777 -e 'print(quotemeta($ENV{'"$newPathVarName"'}))')"
     echo "pathEsc for $newPathVarName: $pathEsc"
@@ -42,6 +42,20 @@ if [[ -e scripts ]]; then
     substitutePath "/usr/local/etc" "emberSysconfdir"
 
     substitutePath "/usr/local/share" "emberDatadir"
+fi
+
+if [[ -e docs ]]; then
+    if ! [[ -d docs ]]; then
+        warn "The \"docs\" folder exists, but is not a directory. Documentation will not be installed."
+    else
+        if ! fmwtk_loc="$(type -P "futuramerlin-web-toolkit-build")" || [[ -z $fmwtk_loc ]]; then
+            warn "Not building documentation: futuramerlin-web-toolkit not found."
+        else
+            pushd "docs" || die
+            futuramerlin-web-toolkit-build
+            popd || die
+        fi
+    fi
 fi
 
 #### End of preparation install script template ####
