Update Git repository using egup-single

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3,6 +3,26 @@
 
 # Should work without ember-shared or crystallize, just in case, so don't source ember_bash_setup or set traps that need
 
+packageName="$(cat package-name)"
+
+eiteDie() {
+    #NOTE: MAINTENANCE: Manual error printing
+    if [[ -z "$(ember-getconf emberSharedVersion)" ]]; then
+        printf '%b' '\033[1;31m' >&2
+        echo "ERROR: ember-shared is not properly installed! It must be installed before installing $packageName." >&2
+        printf '%b' '\033[0m' >&2
+        exit 1
+    fi
+}
+
+if ! ebs_loc="$(type -P "ember_bash_setup")" || [[ -z $ebs_loc ]]; then
+    eiteDie || exit 1
+fi
+
+if [[ -z "$(ember-getconf emberSharedVersion)" ]]; then
+    eiteDie || exit 1
+fi
+
 #NOTE: MAINTENANCE: Manual error printing
 trap 'printf '\''%b'\'' '\''\033[1;31m'\'' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)." >&2; printf '\''%b'\'' '\''\033[0m'\'' >&2; exit 1' ERR
 
diff --git a/support/getDirs b/support/getDirs
--- a/support/getDirs
+++ b/support/getDirs
@@ -4,7 +4,7 @@
 #NOTE: MAINTENANCE: Manual error printing
 if [[ -z "$(ember-getconf emberSharedVersion)" ]]; then
     printf '%b' '\033[1;31m' >&2
-    echo "ERROR: ember-shared is not properly installed! It must be installed before installing eite." >&2
+    echo "ERROR: ember-shared is not properly installed! It must be installed before installing $packageName." >&2
     printf '%b' '\033[0m' >&2
     exit 1
 fi
diff --git a/support/install b/support/install
--- a/support/install
+++ b/support/install
@@ -3,18 +3,18 @@
 source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
 #set -x
 
+packageName="$1"
+shift
+
 #NOTE: MAINTENANCE: Manual error printing
 if [[ -z "$(ember-getconf emberSharedVersion)" ]]; then
     printf '%b' '\033[1;31m' >&2
-    echo "ERROR: ember-shared is not properly installed! It must be installed before installing eite." >&2
+    echo "ERROR: ember-shared is not properly installed! It must be installed before installing $packageName." >&2
     printf '%b' '\033[0m' >&2
     exit 1
 fi
 
 trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)."' ERR
-
-packageName="$1"
-shift
 
 skipConfigFile="false"
 if [[ "$1" == "--skip-config-file" ]]; then
