Update Ember tree

diff --git a/futuramerlin-web-toolkit-build b/futuramerlin-web-toolkit-build
--- a/futuramerlin-web-toolkit-build
+++ b/futuramerlin-web-toolkit-build
@@ -35,7 +35,7 @@ echo "Environment ready; building site..."
     cd "content" || exit
     if [ -f .futuramerlin-web-toolkit/pre-build-hooks ]; then
         echo "Beginning pre-build-hooks..."
-        ./.futuramerlin-web-toolkit/pre-build-hooks || echo "WARNING! pre-build-hooks failed."
+        ./.futuramerlin-web-toolkit/pre-build-hooks || echo "WARNING! pre-build-hooks failed; continuing anyway."
         echo "Done pre-build-hooks."
     fi
     traversedirectory() {
@@ -64,7 +64,7 @@ echo "Environment ready; building site..."
     traversedirectory "."
     if [ -f .futuramerlin-web-toolkit/post-build-hooks ]; then
         echo "Beginning post-build-hooks..."
-        ./.futuramerlin-web-toolkit/post-build-hooks || echo "WARNING! post-build-hooks failed."
+        ./.futuramerlin-web-toolkit/post-build-hooks || echo "WARNING! post-build-hooks failed; continuing anyway."
         echo "Done post-build-hooks."
     fi
 )
