Update Git repository using egup-single

diff --git a/scripts/fmwtk-convpage b/scripts/fmwtk-convpage
--- a/scripts/fmwtk-convpage
+++ b/scripts/fmwtk-convpage
@@ -20,15 +20,17 @@ fi
 
 cp "$infile" "$outfile"
 
-perl -0777 -p -i -e '
-    s/(\n\s*[^-\n]*\n)(\s*- )/\1<ul>\n\2/g; # ul start tags
-    s/(\n\s*[^#\n]*\n)(\s*# )/\1<ul>\n\2/g; # ol start tags
-    s/(\n\s*- [^\n]*\n)(\s*[^-][^ ][^\n]*\n)/\1<\/ul>\n\2/g; # ul end tags
-    s/(\n\s*# [^\n]*\n)(\s*[^#][^ ][^\n]*\n)/\1<\/ul>\n\2/g; # ol end tags
-    s/(\n\s*)- ([^\n]*)\n/\1<li>\2</li>\n/g; # li tags in ul
-    s/(\n\s*)# ([^\n]*)\n/\1<li>\2</li>\n/g; # li tags in ol
-    s/^(\s*)([^<])$/\1<p>\2</p>/g; # paragraph tags
-    ' "$outfile" || die "Substitution failed"
+if [[ "ftm" == "$extension" ]]; then
+    perl -0777 -p -i -e '
+        s/(\n\s*[^-\n]*\n)(\s*- )/\1<ul>\n\2/g; # ul start tags
+        s/(\n\s*[^#\n]*\n)(\s*# )/\1<ul>\n\2/g; # ol start tags
+        s/(\n\s*- [^\n]*\n)(\s*[^-][^ ][^\n]*\n)/\1<\/ul>\n\2/g; # ul end tags
+        s/(\n\s*# [^\n]*\n)(\s*[^#][^ ][^\n]*\n)/\1<\/ul>\n\2/g; # ol end tags
+        s/(\n\s*)- ([^\n]*)\n/\1<li>\2</li>\n/g; # li tags in ul
+        s/(\n\s*)# ([^\n]*)\n/\1<li>\2</li>\n/g; # li tags in ol
+        s/^(\s*)([^<])$/\1<p>\2</p>/g; # paragraph tags
+        ' "$outfile" || die "Substitution failed"
+fi
 
 if [[ "true" == "$stdout" ]]; then
     cat "$outfile"
