Update Ember tree

diff --git a/scripts/futuramerlin-web-toolkit-build b/scripts/futuramerlin-web-toolkit-build
--- a/scripts/futuramerlin-web-toolkit-build
+++ b/scripts/futuramerlin-web-toolkit-build
@@ -1,18 +1,19 @@
 #!/bin/bash
-#Futuramerlin Web Toolkit build script
+source ember_bash_setup &> /dev/null
+trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
+
 #Version:
 export futuramerlinWebToolkitVersion='2.1.2.5.5.1'
 
 shopt -s extglob
-set -e
 
 futuramerlinWebToolkitConfigFileName="/usr/local/etc/futuramerlin-web-toolkit.conf"
 
-if [ -f "$HOME/.futuramerlin-web-toolkit.cfg" ]; then
+if [[ -f "$HOME/.futuramerlin-web-toolkit.cfg" ]]; then
     futuramerlinWebToolkitConfigFileName="$HOME/.futuramerlin-web-toolkit.cfg"
 fi
 
-if [ -f ./.futuramerlin-web-toolkit/.futuramerlin-web-toolkit.cfg ]; then
+if [[ -f ./.futuramerlin-web-toolkit/.futuramerlin-web-toolkit.cfg ]]; then
     futuramerlinWebToolkitConfigFileName="./.futuramerlin-web-toolkit/.futuramerlin-web-toolkit.cfg"
 fi
 
@@ -50,7 +51,7 @@ echo "Environment ready; building site..."
     cd ./source || exit 1
     (
         cd "content" || exit 1
-        if [ -f .futuramerlin-web-toolkit/pre-build-hooks ]; then
+        if [[ -f .futuramerlin-web-toolkit/pre-build-hooks ]]; then
             echo "Beginning pre-build-hooks..."
             ./.futuramerlin-web-toolkit/pre-build-hooks || echo "WARNING! pre-build-hooks failed; continuing anyway."
             echo "Done pre-build-hooks."
@@ -79,7 +80,7 @@ echo "Environment ready; building site..."
             shopt -u dotglob
         }
         traversedirectory "."
-        if [ -f .futuramerlin-web-toolkit/post-build-hooks ]; then
+        if [[ -f .futuramerlin-web-toolkit/post-build-hooks ]]; then
             echo "Beginning post-build-hooks..."
             ./.futuramerlin-web-toolkit/post-build-hooks || echo "WARNING! post-build-hooks failed; continuing anyway."
             echo "Done post-build-hooks."
diff --git a/scripts/futuramerlin-web-toolkit-build-page b/scripts/futuramerlin-web-toolkit-build-page
--- a/scripts/futuramerlin-web-toolkit-build-page
+++ b/scripts/futuramerlin-web-toolkit-build-page
@@ -1,4 +1,6 @@
 #!/bin/bash
+source ember_bash_setup &> /dev/null
+trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 
 shopt -s extglob
 set +H
@@ -42,12 +44,12 @@ ere_quote() {
 }
 export -f ere_quote
 title="$(ere_quote $title)"
-if [ -n "$title" ]; then
+if [[ -n "$title" ]]; then
     replace="s/<title>Ember<\/title>/<title>$title &mdash; Ember<\/title>/g"
     perl -0777 -p -i -e "$replace" "../../built/$1"
 fi
 #Work on home page
-if [ "$Page" == "." ]; then
+if [[ "$Page" == "." ]]; then
     replace="s/<p class=\"logo\">(((?!<\/p>)[\S\s])*)<\/p>/<h1 class=\"logo\">\1<\/h1>/g"
     perl -0777 -p -i -e "$replace" "../../built/$1"
     perl -0777 -p -i -e "s/nav-item-inactive index\"/nav-item-selected\"/g" "../../built/$1"
