Update Git repository using egup-single

diff --git a/scripts/futuramerlin-web-toolkit-build b/scripts/futuramerlin-web-toolkit-build
--- a/scripts/futuramerlin-web-toolkit-build
+++ b/scripts/futuramerlin-web-toolkit-build
@@ -89,25 +89,25 @@ echo "Environment ready; building site..."
             echo "Done pre-build-hooks."
         fi
         if [[ "true" != "$quick" ]]; then
-        tempFile="$(tempFile)"
-        find . \( -name "futuramerlin-web-toolkit-discography.conf" -or -name "fmwtk-discography.conf" \) -print0 > "$tempFile"
-        while IFS= read -r -d '' currentFileName; do
-            fmwtk-discography "$currentFileName"
-        done < "$tempFile"
-        find . \( -name "futuramerlin-web-toolkit-blog.conf" -or -name "fmwtk-blog.conf" \) -print0 > "$tempFile"
-        while IFS= read -r -d '' currentFileName; do
-            fmwtk-blog "$currentFileName"
-        done < "$tempFile"
-        find . \( -name "fmwtk-book.conf" -or -name '*-fmwtk-book.conf' -or -name '*.fmwtk-book.conf' \) -print0 > "$tempFile"
-        while IFS= read -r -d '' currentFileName; do
-            fmwtk-book "$currentFileName"
-        done < "$tempFile"
-        if [[ -f .futuramerlin-web-toolkit/post-book-hooks ]]; then
-            echo "Beginning post-book-hooks..."
-            ./.futuramerlin-web-toolkit/post-book-hooks || warn "Post-book-hooks failed; continuing anyway."
-            echo "Done post-book-hooks."
-        fi
-        rm "$tempFile"
+            tempFile="$(tempFile)"
+            find . \( -name "futuramerlin-web-toolkit-discography.conf" -or -name "fmwtk-discography.conf" \) -print0 > "$tempFile"
+            while IFS= read -r -d '' currentFileName; do
+                fmwtk-discography "$currentFileName"
+            done < "$tempFile"
+            find . \( -name "futuramerlin-web-toolkit-blog.conf" -or -name "fmwtk-blog.conf" \) -print0 > "$tempFile"
+            while IFS= read -r -d '' currentFileName; do
+                fmwtk-blog "$currentFileName"
+            done < "$tempFile"
+            find . \( -name "fmwtk-book.conf" -or -name '*-fmwtk-book.conf' -or -name '*.fmwtk-book.conf' \) -print0 > "$tempFile"
+            while IFS= read -r -d '' currentFileName; do
+                fmwtk-book "$currentFileName"
+            done < "$tempFile"
+            if [[ -f .futuramerlin-web-toolkit/post-book-hooks ]]; then
+                echo "Beginning post-book-hooks..."
+                ./.futuramerlin-web-toolkit/post-book-hooks || warn "Post-book-hooks failed; continuing anyway."
+                echo "Done post-book-hooks."
+            fi
+            rm "$tempFile"
         fi
         find . -type d -empty -delete
         traversedirectory() {
