Update Git repository using egup-single

diff --git a/scripts/futuramerlin-web-toolkit-build-book b/scripts/futuramerlin-web-toolkit-build-book
--- a/scripts/futuramerlin-web-toolkit-build-book
+++ b/scripts/futuramerlin-web-toolkit-build-book
@@ -64,20 +64,22 @@ adjustAssets() {
     inputFileDir="$(dirname "$inputFilePath")"
     local currentItem
     local assetName
-    grep -o -e '<img src="[^"]*"' "$fileName" | while IFS= read -r currentItem; do
-        assetName="${currentItem%\"}"
-        assetName="${assetName/<img src=\"}"
-        assetNameEscaped="${assetName//\//\\\/}"
-        assetPath="$(realpath "$inputFileDir/$assetName")"
-        assetRelativePath="${assetPath/$rootPath}"
-        assetExtension="${assetRelativePath//*.}"
-        assetHash="$(sha512sum <<< "$assetRelativePath" | awk '{print $1;}')"
-        cp "$assetPath" "$outFileDir/assets/$assetHash.$assetExtension"
-        perl -0777 -p -i -e '
-            s/<img src="'"$assetNameEscaped"'"/<img src="'"assets\/$assetHash.$assetExtension"'"/g;
-            ' "$fileName" || die "Substitution failed"
-    done
-    true
+    if grep -o -e '<img src="[^"]*"' "$fileName" > /dev/null; then
+        grep -o -e '<img src="[^"]*"' "$fileName" | while IFS= read -r currentItem; do
+            assetName="${currentItem%\"}"
+            assetName="${assetName/<img src=\"}"
+            assetNameEscaped="${assetName//\//\\\/}"
+            assetPath="$(realpath "$inputFileDir/$assetName")"
+            assetRelativePath="${assetPath/$rootPath}"
+            assetExtension="${assetRelativePath//*.}"
+            assetHash="$(sha512sum <<< "$assetRelativePath" | awk '{print $1;}')"
+            cp "$assetPath" "$outFileDir/assets/$assetHash.$assetExtension"
+            perl -0777 -p -i -e '
+                s/<img src="'"$assetNameEscaped"'"/<img src="'"assets\/$assetHash.$assetExtension"'"/g;
+                ' "$fileName" || die "Substitution failed"
+        done
+        #true
+    fi
 }
 
 convertBookFile() (
